/* CHARACTERS */
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';

/* CHARACTER */
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const CLEAR_CHARACTER = 'CLEAR_CHARACTER';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';